# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

#
# The intent of the "shared" profile is to provide a convenient way to run other applications of SWIYU
# so they are linked to each other and do not conflict with ports. E.g.
# swiyu-registry-trust-authoring-service The shared profile is to be used together with local as described in readme.md.
#

spring:
  datasource: # the datasource from authoring service
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5380/trust-registry-db"
    username: "postgres"
    password: "secret"
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
  docker:
    compose:
      enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE